name: ipark
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  flutter_credit_card: ^4.0.1
  mobx: ^2.5.0
  flutter_mobx: any
  pull_to_refresh_flutter3: ^2.0.2
  dio: ^5.7.0
  get_it: ^8.0.3
  json_annotation: any
  ionicons: ^0.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: any
  json_serializable: any
  mobx_codegen: any
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
